<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Wordset.Domain\Wordset.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Wordset.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
