// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wordset.Infrastructure.Data;

#nullable disable

namespace Wordset.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WordsetDbContext))]
    [Migration("20260610155425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wordset.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("WordsetId")
                        .HasColumnType("uuid")
                        .HasColumnName("wordset_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_rank");

                    b.HasKey("WordsetId", "Value");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("Wordset.Domain.Entities.Wordset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("share_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.ToTable("wordsets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
